# Generated by Django 4.2.23 on 2025-06-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='note',
        ),
    ]
