# Generated by Django 4.2.23 on 2025-06-15 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_patient_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
