version: '3.9'

services:
  # MySQL riêng cho patient-service
  mysql-patient:
    image: mysql:8.0
    container_name: mysql-patient
    restart: always
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: patient_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"  # nếu bạn muốn truy cập từ máy host
    volumes:
      - mysql_patient_data:/var/lib/mysql
    networks:
      - healthnet

  patient-service:
    container_name: patient-service
    build:
      context: ./patient-service
    volumes:
      - ./patient-service:/code
    ports:
      - "8000:8000"
    networks:
      - healthnet
    depends_on:
      - mysql-patient
    environment:
      - DEBUG=1

  doctor-service:
    container_name: doctor-service
    build:
      context: ./doctor-service
    volumes:
      - ./doctor-service:/code
    ports:
      - "8002:8000"
    networks:
      - healthnet
    environment:
      - DEBUG=1

  appointment-service:
    container_name: appointment-service
    build:
      context: ./appointment-service
    volumes:
      - ./appointment-service:/code
    ports:
      - "8001:8000"
    depends_on:
      - patient-service
      - doctor-service
    networks:
      - healthnet
    environment:
      - DEBUG=1

volumes:
  mysql_patient_data:

networks:
  healthnet:
    driver: bridge
